### ISSUE TITLE
specify .net version 4.5 or 4.5.1

### ISSUE THREAD

**Issue by itajaja** [stevewillcock/grunt-msbuild#21]
It seems that it's not possible to set the version as `4.5` or `4.5.1`.
[Here](https://github.com/stevewillcock/grunt-msbuild/blob/master/tasks/msbuild.js#L12) I can see that the version array is set only up to 4.0.

**Comment by whyleee** [comment]
.NET 4.5 and 4.5.1 are in-place upgrades of .NET 4.0. They overwrite files in "v.4.0.30319" folder. So after you installed .NET 4.5 or 4.5.1 on the target machine, 4.0 targeted projects will use updated 4.5 or 4.5.1 .NET dll's anyway.

That's why you can't choose between 4.* versions. Version `4.0` in config means any 4.* .NET installed on the target machine.

**Comment by itajaja** [comment]
You are correct, I figured that out and I didn't come back to close the issue :blush:
