### ISSUE TITLE
Package Restore

### ISSUE THREAD

**Issue by paulcbetts** [stevewillcock/grunt-msbuild#27]
It'd be cool if grunt-msbuild did a NuGet Package Restore before it invoked msbuild (just shell out to `nuget restore`)

**Comment by stevewillcock** [comment]
Hi Paul,

I think you are right, this would make sense as an opt-in flag in the configuration. For internal use we are calling nuget package restore in a grunt-shell task but this would certainly reduce the friction when using grunt-msbuild.

The default behaviour would be to call `nuget restore` as you say but on a build server nuget might not be on the path and it would require something like `mono /path/to/nuget restore` or even `/path/to/mono /path/to/nuget restore` for mono builds so it may need some optional config settings for that.

I'll take a look :)

**Comment by paulcbetts** [comment]
> The default behaviour would be to call nuget restore as you say but on a build server nuget might not be on the path

Bundle it in your npm package :)

**Comment by stevewillcock** [comment]
That's a great idea - I wonder if there would be any licensing issues with including it? I'll investigate.

**Comment by stevewillcock** [comment]
It looks like NuGet is Apache licensed:

https://nuget.codeplex.com/license
https://github.com/NuGet/NuGet3/blob/dev/LICENSE.txt

So that should be fine :)

**Comment by stevewillcock** [comment]
I just came to implement this (suddenly urgent as I needed it for a project here) but I did a quick check and there's already a separate grunt package to perform a nuget install - https://www.npmjs.com/package/grunt-nuget-install

This seems to work very well and the setup required is minimal so in the spirit of keeping node modules small and focused (but mostly in the spirit of avoiding extra work where possible) I'm going to recommend using the grunt-nuget-install package rather than adding nuget restore functionality to this module. That's what I'm doing for the build which I'm setting up here and it's fine so far.

Thanks

Steve
