### ISSUE TITLE
Explicit path to msbuild - msbuildPath - is mandatory

### ISSUE THREAD

**Issue by sherland** [stevewillcock/grunt-msbuild#47]
We have a lot of diversity in configuration of build-machines and developer-machines. After installing VS2019, the previous version of grunt-msbuild started to fail due to #45 

Making msbuildPath mandatory is blocking us from upgrading, since our 40-50 developers and 20+ teamcity/ azure devops build-machines does not have msbuild.exe at same location.

-
It must be frustrating to keep up with all the changes, but the complexity has to live somewhere...

**Comment by stevewillcock** [comment]
Hi @sherland, thanks for raising the issue. One approach that you could take here is to set the path for msbuild in the %PATH% / $PATH environment variable on your build machines (globally or at the top of your build script) and then to simply set the msbuildPath value for the plugin to "msbuild". As you say the complexity does make this difficult to maintain especially when the approach from MS seems to change with every release.

**Comment by mariusandersen** [comment]
This %PATH% approach might work OK on build machines but this would mean every single developer needs to set %PATH% before running grunt. The whole point of grunt is to make it simple for developers - run "yarn" then "grunt" and you're set!

Are you suggesting that everyone that use grunt-msbuild needs to have a seperate grunt step before running grunt-msbuild where env variable is set? 

This just means everyone using your package has to maintain this localization themselves. Individual developers can have Professional version or Enterprice version installed. Can have 2017 or 2019 installed. All factors changing what path msbuild has. It's not very convenient that all these checks needs to be maintained locally.

**Comment by stevewillcock** [comment]
Hi @mariusandersen, I understand the pain here. From my perspective one main point of grunt (I'm not sure there's just one 'whole point', it's a multi-faceted tool and I'm sure people use it in lots of different ways) is that it provides a way to run automated tasks in a repeatable and predictable way and that's still possible after this change (I'd argue that it's now more repeatable and predictable as external changes to VS environments on a dev or build machine won't risk breaking the build by suddenly pointing at a different version of MSBuild) . Getting set up fast is definitely important but it has become quite difficult to achieve the automatic detection of MSBuild location with the changes that occur with each VS release and for me the costs of updating and testing this with each VS / SDK release outweigh the inconvenience of setting a PATH variable.

If someone were to submit a PR that reinstated the automatic VS version lookup behind a configuration flag (and to make this work for the latest VS / SDK versions) I'd certainly welcome that but it's unlikely that I'll have the time to do this myself in the near future.

On another note, for any new dotnet projects I'm now tending to use https://fake.build/ as a task runner rather than Grunt (mostly for the type-safety aspects) and it's something that I'd recommend anyone looking at automation of dotnet builds to evaluate.

**Comment by stevewillcock** [comment]
PR merged (thanks to @canpolat) which should address this issue. Published to npm as 1.1.0. Please let me know if this resolves the issue for you or if you come across any problems with this. Thanks!

**Comment by ViceIce** [comment]
Can we set infer to default, if no msbuildpath is set? Then it would just work as before v1.

**Comment by stevewillcock** [comment]
@ViceIce Yes, I think so, seems like it shouldn't cause a problem to do that, I'll take a look when I get chance. Of course it won't work _quite_ the same as this version will work with newer versions of VS and MSBuild but the API would be backwards compatible with pre 1.0.

**Comment by ViceIce** [comment]
I think that would be no problem for us, thankfully our current minimum vs version is 2017.
